"""empty message

Revision ID: 65372c743204
Revises: 461de817e3d2
Create Date: 2021-07-26 12:40:58.373847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65372c743204'
down_revision = '461de817e3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('price', sa.String(length=50), nullable=True))
    op.add_column('menu', sa.Column('quantity', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'quantity')
    op.drop_column('menu', 'price')
    # ### end Alembic commands ###
